# This workflow tests and builds the .NET project. It runs on every pull request to the main branch.

name: .NET Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["3.1.x", "6.0.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Install dependencies
        working-directory: ./backend
        run: dotnet restore

      - name: Build
        working-directory: ./backend
        run: dotnet build

      - name: Test with the dotnet CLI
        working-directory: ./backend
        run: dotnet test
